DROP TABLE IF EXISTS NOTIFICATION;
 
CREATE TABLE NOTIFICATION (
  NOTIFICATION_ID BIGINT NOT NULL,
  TITLE VARCHAR(25) NOT NULL,
  DESCRIPTION VARCHAR(60) NOT NULL,
  PUBLICATION DATE NOT NULL,
  VISUALIZATION DATE NOT NULL
);
COMMIT;

CREATE UNIQUE INDEX NOTIFICATION_IX ON NOTIFICATION(NOTIFICATION_ID);

INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (1,'NOTIFICATION TITLE 1','NOTIFICATION DESCRIPTION 1','2020-01-01','2020-02-01');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (2,'NOTIFICATION TITLE 2','NOTIFICATION DESCRIPTION 2','2020-01-02','2020-02-02');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (3,'NOTIFICATION TITLE 3','NOTIFICATION DESCRIPTION 3','2020-01-03','2020-02-03');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (4,'NOTIFICATION TITLE 4','NOTIFICATION DESCRIPTION 4','2020-01-04','2020-02-04');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (5,'NOTIFICATION TITLE 5','NOTIFICATION DESCRIPTION 5','2020-01-05','2020-02-05');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (6,'NOTIFICATION TITLE 6','NOTIFICATION DESCRIPTION 6','2020-01-06','2020-02-06');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (7,'NOTIFICATION TITLE 7','NOTIFICATION DESCRIPTION 7','2020-01-07','2020-02-07');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (8,'NOTIFICATION TITLE 8','NOTIFICATION DESCRIPTION 8','2020-01-08','2020-02-08');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (9,'NOTIFICATION TITLE 9','NOTIFICATION DESCRIPTION 9','2020-01-09','2020-02-09');
INSERT INTO NOTIFICATION (NOTIFICATION_ID, TITLE, DESCRIPTION, PUBLICATION, VISUALIZATION) VALUES (10,'NOTIFICATION TITLE 10','NOTIFICATION DESCRIPTION 10','2020-01-10','2020-02-10');
COMMIT;  






